(function() {
  const btn = document.getElementById('langToggle');
  if (!btn) return;

  const dict = { // TODO: переделать на нормальное
    ru: {
      // ===== NAV =====
      'nav.home': 'Главная',
      'nav.projects': 'Проекты',
      'nav.stories': 'Истории',
      'nav.gallery': 'Галерея',
      'nav.about': 'Обо мне',
      'nav.contact': 'Контакты',

      // ===== PROJECTS DROPDOWN =====
      'project.1': 'Alpha Browser',
      'project.2': 'Ten Assistant',
      'project.3': 'Marketplace Simulator',
      'project.4': 'AI Auto-Responder Bot',
      'project.5': 'Physics Tests',
      'project.6': 'Telegram Chat Analyzer',
      'project.7': 'Telegram Channel Bots',
      'project.8': 'Portfolio Website',

      // ===== STORIES DROPDOWN =====
      'story.1': 'Первая попытка',
      'story.2': 'Империя, которая не выросла',
      'story.3': '2025 год. Мой путь в колледж',
      'story.4': 'Почему я сделал Альфу',

      // ===== HERO =====
      'hero.available': '● Доступен для проектов',
      'hero.city': '📍 Коломна, Россия',
      'hero.stack': '💻 Python · JS · C++',
      'hero.greeting': 'Привет, я',
      'hero.name': 'Юра',
      'hero.desc': 'Разработчик из Коломны. Пишу на Python, JavaScript и C++. Учусь в Аграрном колледже им. Н. Т. Козлова. Собираю проекты и записываю истории.',
      'hero.quote': '«Всему своё время»',
      'hero.btn.projects': 'Смотреть работы',
      'hero.btn.contact': 'Связаться',

      // ===== SECTIONS =====
      'section.works': 'Мои',
      'section.works.accent': 'работы',
      'section.works.all': 'все проекты →',
      'section.stories': 'Мои',
      'section.stories.accent': 'истории',
      'section.stories.all': 'все истории →',
      'section.skills': 'Мои',
      'section.skills.accent': 'навыки',
      'section.stats': 'Обо мне в',
      'section.stats.accent': 'цифрах',
      'section.now': 'Сейчас работаю над',
      'section.reviews': 'Что обо мне',
      'section.reviews.accent': 'говорят',
      'section.faq': 'Частые',
      'section.faq.accent': 'вопросы',
      'section.timeline': 'Мой',
      'section.timeline.accent': 'путь',
      'section.gallery.accent': 'Галерея',
      'section.gallery.all': 'вся галерея →',
      'section.contact': 'Связаться',
      'section.contact.accent': 'со мной',

      // ===== WORKS =====
      'work.more': 'Подробнее',
      'work.p1.cat': 'Electron · JS',
      'work.p1.title': 'Alpha Browser',
      'work.p1.desc': 'Свой браузер на Electron: вкладки, история поиска, загрузки, кастомизация интерфейса. Полностью под моим контролем — ничего не сливает.',
      'work.p2.cat': 'Python · AI',
      'work.p2.title': 'Ten Assistant',
      'work.p2.desc': 'Настольный помощник с локальным ИИ: открывает приложения, работает с папками, пишет в Telegram от лица бота. Помнит контекст, модель можно заменить.',
      'work.p3.cat': 'HTML · CSS · JS',
      'work.p3.title': 'Marketplace Simulator',
      'work.p3.desc': 'Веб-сайт в стиле DNS: каталог товаров, корзина, регистрация и вход с паролем. Полноценный интернет-магазин — только для себя.',

      // ===== STORIES PREVIEW =====
      'story.prev.1.date': '2023-2024',
      'story.prev.1.title': 'Первая попытка',
      'story.prev.1.desc': 'Как я пытался освоить Unity, забросил, вернулся к Python и написал свой первый скрипт.',
      'story.prev.2.date': 'Октябрь 2025',
      'story.prev.2.title': 'Империя, которая не выросла',
      'story.prev.2.desc': '5 Telegram-каналов с автопостингом через локальный ИИ. Каналы не взлетели.',
      'story.prev.3.date': '2025',
      'story.prev.3.title': '2025 год. Мой путь в колледж',
      'story.prev.3.desc': 'Как я поступил в Аграрный колледж, что там изучаю и почему это связано с программированием.',

      // ===== STATS =====
      'stats.projects': 'Проектов',
      'stats.stories': 'Истории',
      'stats.langs': 'Языка',
      'stats.start': 'Год старта',

      // ===== NOW WORKING =====
      'now.cat': '● Сейчас работаю над',
      'now.title': 'Сайт-портфолио (этот сайт)',
      'now.desc': 'Собираю личный сайт-портфолио с интерактивами, тёмной темой и переключателем языка. Делаю всё сам: HTML, CSS, JS.',

      // ===== FAQ =====
      'faq.q1': 'Кто ты и чем занимаешься?',
      'faq.a1': 'Я Юра, разработчик из Коломны. Пишу на Python, JavaScript и C++. Учусь в Аграрном колледже им. Н. Т. Козлова. Делаю проекты разного уровня: от ботов до браузеров.',
      'faq.q2': 'Какие языки программирования знаешь?',
      'faq.a2': 'Основные — Python, JavaScript и C++. Дополнительно: HTML/CSS, Git, Linux, Electron. Работаю с локальными ИИ-моделями. Постоянно учусь новому.',
      'faq.q3': 'Можно заказать у тебя проект?',
      'faq.a3': 'Да, я открыт к предложениям. Напиши в Telegram (@ArishaBii) или на email — обсудим задачу, сроки и стоимость.',
      'faq.q4': 'Как с тобой связаться?',
      'faq.a4': 'Telegram (@ArishaBii), GitHub (NekitTRF) или email (nekit19980@gmail.com). Все контакты — на странице «Контакты» или в футере.',
      'faq.q5': 'Ты работаешь только в Коломне?',
      'faq.a5': 'Нет, я работаю удалённо. Могу делать проекты для заказчиков из любого города.',
      'faq.q6': 'Сколько стоит проект?',
      'faq.a6': 'Зависит от задачи. Напиши, что нужно — обсудим детали и договоримся. Небольшие проекты делаю быстро.',

      // ===== TIMELINE =====
      'tl.2024.year': '2024',
      'tl.2024.text': '<b>Начал программировать.</b> Первые скрипты на Python, первые ошибки, первое «оно работает!».',
      'tl.2025a.year': '2025',
      'tl.2025a.text': '<b>Поступил в Аграрный колледж им. Н. Т. Козлова.</b> Там же — первый серьёзный проект и знакомство с C++.',
      'tl.2025b.year': '2025',
      'tl.2025b.text': '<b>Сделал боты для Telegram-каналов.</b> 5 тематик, локальный ИИ, автопостинг. Первый опыт реальной автоматизации.',
      'tl.2026.year': '2026',
      'tl.2026.text': '<b>Год проектов.</b> Браузер Альфа, настольный помощник Ten, симулятор маркетплейса, аналитика чатов. И этот сайт.',
      'tl.now.year': 'Сейчас',
      'tl.now.text': '<b>Продолжаю делать.</b> Пишу код, учусь новому, собираю портфолио. Дальше — больше.',

      // ===== CONTACT =====
      'contact.telegram': 'Telegram',
      'contact.telegram.desc': '@ArishaBii — самый быстрый способ',
      'contact.github': 'GitHub',
      'contact.github.desc': 'github.com/NekitTRF — мои проекты',
      'contact.email': 'Email',
      'contact.email.desc': 'nekit19980@gmail.com — для серьёзных дел',
      'contact.location': 'Локация',
      'contact.location.desc': 'Коломна, Россия',

      // ===== FORM =====
      'form.name': 'Имя',
      'form.name.placeholder': 'Как тебя зовут?',
      'form.email': 'Email',
      'form.email.placeholder': 'example@mail.com',
      'form.message': 'Сообщение',
      'form.message.placeholder': 'Опиши задачу или просто напиши привет...',
      'form.send': 'Отправить сообщение',

            // ===== REVIEWS =====
      'rev.1.text': '«Юра — нормальный студент. Работы сдаёт вовремя, не прогуливает. Математику понимает, не просто зубрит. Иногда слишком серьёзный — но это скорее плюс.»',
      'rev.1.name': 'Ольга',
      'rev.1.role': 'Преподаватель колледжа',
      'rev.2.text': '«С Юрой мы учимся вместе уже второй курс. Он тот самый человек, который никогда не прогуливает пары и всегда в курсе, что задали. Если я что-то пропустил — иду к нему. Правда, отвечает не сразу, вечно в своих проектах копается. Но объясняет нормально, без понтов.»',
      'rev.2.name': 'Тимофей',
      'rev.2.role': 'Одногруппник',
      'rev.3.text': '«Юра — ответственный и самостоятельный студент. За два года обучения ни одного пропуска без уважительной причины. Всегда выполняет то, что обещает — иногда даже больше, чем нужно. У него есть чёткая цель и план на будущее, что редкость для его возраста. Единственное — иногда он берёт на себя слишком много, из-за чего выгорает. Но это проходит. Рекомендую как надёжного и целеустремлённого человека.»',
      'rev.3.name': 'Регина',
      'rev.3.role': 'Куратор',
      'rev.4.text': '«Работал с ним над портфолио. Если что-то не работает — не бросает, копает до конца. Может часами сидеть над одной строчкой. Упрямый. Мне нравится.»',
      'rev.4.name': 'ARIA',
      'rev.4.role': 'Наставник',
      // ===== TERMINAL =====
      'term.placeholder': '> напиши что-нибудь...',
      'term.status': '$ печатай что хочешь',
      'term.status.ready': '$ жми «ОТОРВАТЬ» когда готов',
      'term.status.max': '$ максимум 8 строк, жми ОТОРВАТЬ',
      'term.status.phys': '$ хватай буквы мышкой и кидай',
      'term.reset': 'СБРОС',
      'term.tear': 'ОТОРВАТЬ',
      'term.on': 'ON',
            'page.projects.title': 'Мои',
      'page.projects.title.accent': 'проекты',
      'page.projects.subtitle': 'Всё, что я делал: от простых скриптов до полноценных проектов. Python, JavaScript, C++.',
      'filter.all': 'Все',
      'filter.python': 'Python',
      'filter.js': 'JavaScript',
      'filter.cpp': 'C++',
      'work.p4.cat': 'Python · AI',
      'work.p4.title': 'AI Auto-Responder Bot',
      'work.p4.desc': 'Telegram-бот через Business Mode, отвечает за меня на базе локального ИИ.',
      'work.p5.cat': 'HTML · CSS · JS',
      'work.p5.title': 'Physics Tests',
      'work.p5.desc': 'Сборник интерактивных тестов по физике и медицине. Экзамен, навигация, картинки.',
      'work.p6.cat': 'Python',
      'work.p6.title': 'Telegram Chat Analyzer',
      'work.p6.desc': 'Локальный скрипт для анализа ТГ-чатов: топ флудеров, медиа, слова, HTML-отчёт.',
      'work.p7.cat': 'Python · AI',
      'work.p7.title': 'Telegram Channel Bots',
      'work.p7.desc': 'Сборка ботов для 5 тематических каналов с автогенерацией постов.',
      'work.p8.cat': 'HTML · CSS · JS',
      'work.p8.title': 'Portfolio Website',
      'work.p8.desc': 'Этот сайт: частицы, терминал с физикой букв, темы, RU/EN.',
            'page.gallery.title': 'Галерея',
      'page.gallery.subtitle': 'Скриншоты проектов, фото с работы над кодом, просто атмосферные кадры. Клик — увеличить.',

      'page.about.title': 'Обо',
      'page.about.title.accent': 'мне',
      'page.about.p1': 'Меня зовут Юра. Я разработчик из Коломны, учусь в Аграрном колледже имени Н. Т. Козлова. Пишу на Python, JavaScript и C++.',
      'page.about.p2': 'Начал программировать в 2024 году с простых скриптов на Python. Сейчас делаю более серьёзные проекты: от Telegram-ботов до веб-сайтов. Всё, что умею — выучил сам, через практику и ошибки.',
      'page.about.p3': 'Люблю чистый код, понятные интерфейсы и задачи, которые заставляют думать. Веду этот сайт, чтобы показывать свои работы и делиться историями.',
      'page.about.p4': 'Мне 16, и я учусь в колледже. Пишу код каждый день, пробую новое и делаю проекты, которые мне интересны. Верю, что лучший способ научиться — делать.',

      'page.about.skills': 'Что я',
      'page.about.skills.accent': 'умею',
      'page.about.facts': 'Немного',
      'page.about.facts.accent': 'фактов',

      'fact.1': 'Дата рождения: 17 января 2010',
      'fact.2': 'Живу в Коломне, Россия',
      'fact.3': 'Учусь в Аграрном колледже им. Н. Т. Козлова (с 2025 года)',
      'fact.4': 'Пишу код с 2024 года',
      'fact.5': 'Основной стек: Python, JavaScript, C++',
      'fact.6': 'Работаю с локальными ИИ-моделями',
      'fact.7': 'Люблю тёмные темы интерфейсов (этот сайт — не исключение)',
      'fact.8': 'Открыт к предложениям о работе и сотрудничестве',

      'page.contact.title': 'Связаться',
      'page.contact.title.accent': 'со мной',
      'page.contact.subtitle': 'Пиши по любому вопросу: заказать проект, задать вопрос, просто поздороваться. Отвечаю обычно в течение дня.',

      'project.back': '← Все проекты',
      'project.about': 'О',
      'project.about.accent': 'проекте',
      'project.why': 'Зачем',
      'project.why.accent': 'я его сделал',
      'project.features': 'Что',
      'project.features.accent': 'умеет',
      'project.how': 'Как',
      'project.how.accent': 'работает',
      'project.code': 'Фрагмент',
      'project.code.accent': 'кода',
      'project.gallery': 'Галерея',
      'project.links': 'Ссылки',
      'project.soon': 'Репозиторий скоро появится',
      'project.github': 'Открыть на GitHub',
      'project.demo': 'Попробовать в Telegram',

      'story.back': '← Все истории',
      'story.read.next': 'Читать',
      'story.read.next.accent': 'дальше',
      'story.ps.title': 'P.S.',
      'story.ps.motto': 'Мой девиз: думай, говори, делай',
      'story.ps.p1': 'Наверное, стоит объяснить, зачем я вообще это пишу. Для меня программирование - это не просто код, это возможность создавать что-то своё, понимать, как всё устроено изнутри, и не зависеть от чужих решений.',
      'story.ps.p2': 'Как когда-то я собрал свой первый компьютер, так сейчас я собираю свои первые проекты.',

      'tag.story.path': 'История пути',
      'tag.story.project': 'История проекта',
      'tag.study': 'Про учёбу',
      'read.4min': '4 мин чтения',
      'read.3min': '3 мин чтения',
      'read.2min': '2 мин чтения',
      'read.1min': '1 мин чтения',
      'date.may.2026': 'Май 2026',
      'project.type.personal': 'Личный проект',
            'project.1.about.text': 'Alpha Browser — мой собственный браузер на Electron. Полноценное десктопное приложение с вкладками, историей поиска, менеджером загрузок и кастомизацией интерфейса. Всё под моим контролем — ничего не сливает данные третьим лицам.',
      'project.1.why.text': 'Мой основной браузер (не буду называть название) однажды слил мои пароли — и у меня увели пару аккаунтов. Я разозлился, сел и подумал: а почему бы не сделать свой? Так появился Alpha.',
      'project.1.features.1': 'Вкладки — открытие, закрытие, переключение',
      'project.1.features.2': 'История поиска и посещённых страниц',
      'project.1.features.3': 'Менеджер загрузок с прогрессом',
      'project.1.features.4': 'Кастомизация интерфейса: темы, шрифты, расположение элементов',
      'project.1.features.5': 'Работает офлайн — данные хранятся локально',
      'project.1.features.6': 'Никаких трекеров и аналитики',
      'project.1.how.text': 'Alpha построен на Electron — это позволяет использовать веб-технологии (HTML, CSS, JavaScript) для создания десктопного приложения. Основные вкладки — это <code>webview</code> теги, каждый со своей сессией. История и загрузки хранятся в localStorage и IndexedDB.',
      'project.1.code.comment': '// Создание новой вкладки',
            'project.type.study': 'Учебный проект',
      'project.type.open': 'Open Source',

      'project.2.about.text': 'Ten — настольный голосовой помощник, который живёт на моём компьютере. Работает на базе локального ИИ, помнит контекст, умеет открывать приложения, работать с папками, писать в Telegram от лица бота и открывать сайты.',
      'project.2.why.text': 'Я посмотрел фильм про Железного человека и подумал: а почему у меня нет своего Джарвиса? Так появился Ten. Хотел, чтобы был помощник, который реально помогает, а не просто отвечает на вопросы.',
      'project.2.features.1': 'Открывает приложения по голосовой или текстовой команде',
      'project.2.features.2': 'Работает с папками: создаёт, перемещает, удаляет файлы',
      'project.2.features.3': 'Открывает сайты в браузере',
      'project.2.features.4': 'Пишет в Telegram от лица бота',
      'project.2.features.5': 'Работает с локальным ИИ — модель можно заменить',
      'project.2.features.6': 'Имеет память: помнит, что я говорил раньше',
      'project.2.features.7': 'Понимает контекст, а не просто отдельные команды',
      'project.2.how.text': 'Ядро написано на <code>Python</code>. Для распознавания команд используется локальный ИИ (можно подключить разные модели через Ollama или LM Studio). Интерфейс — на <code>HTML</code> и <code>CSS</code>, обёрнут в простое окно. Память хранится в JSON-файле, вся логика разбита на модули.',
      'project.2.code.comment': '# Обработка команды через локальный ИИ',

      'project.3.about.text': 'Marketplace Simulator — веб-сайт в стиле DNS. Каталог товаров, корзина, регистрация и вход с паролем. Полноценный интернет-магазин, только для себя.',
      'project.3.why.text': 'Идея простая: я хотел купить кучу вещей, но не мог. Тогда я сделал свой маркетплейс — чтобы хотя бы виртуально положить всё в корзину.',
      'project.3.features.1': 'Каталог товаров с категориями',
      'project.3.features.2': 'Корзина: добавить, удалить, изменить количество',
      'project.3.features.3': 'Подсчёт итоговой суммы',
      'project.3.features.4': 'Регистрация и вход с паролем',
      'project.3.features.5': 'Сохранение корзины между сессиями',
      'project.3.features.6': 'Адаптив под мобильные',
      'project.3.how.text': 'Чистый <code>HTML</code>, <code>CSS</code> и <code>JavaScript</code> без фреймворков. Товары описаны в JS-массиве, корзина и пользователи хранятся в <code>localStorage</code>. Авторизация — простая, локальная (для реального сайта нужен сервер, но здесь цель — попрактиковаться).',
      'project.3.code.comment': '// Добавление товара в корзину',

      'project.4.about.text': 'Telegram-бот, который через Business Mode отвечает за меня. Работает на локальном ИИ, понимает контекст, запоминает сообщения. Режимы ответов и промпты настраиваются прямо в Telegram.',
      'project.4.why.text': 'Мне просто устали написывать люди. Постоянно одно и то же, постоянно надо отвечать. Я подумал: а что если бот будет отвечать за меня — и делать это разумно, а не шаблонно?',
      'project.4.features.1': 'Отвечает за меня через Telegram Business Mode',
      'project.4.features.2': 'Работает на локальном ИИ — данные не уходят в облако',
      'project.4.features.3': 'Понимает контекст разговора',
      'project.4.features.4': 'Запоминает сообщения в JSON-файле',
      'project.4.features.5': 'Разные режимы ответов (формальный, дружеский, короткий)',
      'project.4.features.6': 'Управление прямо в Telegram: смена промптов, режимов',
      'project.4.how.text': 'Ядро на <code>Python</code> + библиотека для работы с Telegram Bot API. Через Business Mode бот подключается к моим личным чатам. Каждое входящее сообщение отправляется в локальный ИИ, ответ возвращается и отправляется от моего имени. Все сообщения сохраняются в <code>memory.json</code> для контекста.',
      'project.4.code.comment': '# Обработка входящего сообщения',

      'project.5.about.text': 'Сборник интерактивных тестов по физике и медицине. Каждый тест — отдельная HTML-страница с вопросами, вариантами ответов и подсчётом результата. Есть режим экзамена и навигация по разделам.',
      'project.5.why.text': 'Готовился к экзаменам и понял, что зубрить скучно. Сделал тесты, чтобы проверять себя и заодно потренироваться в вёрстке. Потом добавил раздел по медицине — просто потому что было интересно.',
      'project.5.features.1': 'Тесты по физике атома, ядра, волновой и квантовой оптике, радиосвязи',
      'project.5.features.2': 'Тест по медицине',
      'project.5.features.3': 'Режим экзамена',
      'project.5.features.4': 'Навигация между разделами',
      'project.5.features.5': 'Картинки антенн (нарисовал сам в SVG)',
      'project.5.features.6': 'Подсчёт баллов и вывод результата',
      'project.5.how.text': 'Каждый тест — отдельный <code>HTML</code>-файл со встроенными вопросами и логикой на <code>JavaScript</code>. Стили вынесены, картинки — SVG. Никаких библиотек, всё написано с нуля.',
      'project.5.code.comment': '// Проверка ответа в тесте',

      'project.6.about.text': 'Локальный скрипт для анализа Telegram-чатов. Работает с JSON-экспортом из Telegram Desktop — интернет не нужен, токены не требуются. Считает статистику, строит графики и генерит красивый тёмный HTML-отчёт.',
      'project.6.why.text': 'Мне стало интересно, что происходит в чатах, где я сижу. Кто пишет больше всех, в какое время, какие слова использует. Написал скрипт — и получил кучу инсайтов.',
      'project.6.features.1': 'Общая статистика: всего сообщений, текста, медиа, средняя длина',
      'project.6.features.2': 'Медиа по категориям: фото, стикеры, голосовые, кружочки, гифки',
      'project.6.features.3': 'Топ-5 самых активных участников (флудеров)',
      'project.6.features.4': 'Почасовой график активности за сутки',
      'project.6.features.5': 'Раскладка по дням недели',
      'project.6.features.6': 'Топ-10 частых слов (со стоп-листом предлогов и союзов)',
      'project.6.features.7': 'Тёмный HTML-отчёт со всеми графиками',
      'project.6.how.text': 'Заходишь в Telegram Desktop → нужный чат → Экспорт истории → выбираешь JSON. Кидаешь <code>result.json</code> в папку со скриптом, запускаешь <code>python chat_analytics.py</code>. Скрипт парсит данные и создаёт <code>chat_report.html</code>.',
      'project.6.code.comment': '# Топ-5 самых активных участников',

      'project.7.about.text': 'Сборка ботов для 5 тематических Telegram-каналов: история, психология, финансы, конспирология, карьера. Каждый бот через локальный ИИ генерирует тему, пишет текст, рисует картинку и сам публикует пост в канал.',
      'project.7.why.text': 'Я хотел построить империю автоматизированных Telegram-каналов. Чтобы всё работало само: темы генерируются, картинки рисуются, посты публикуются. Идея была — запустить 5 каналов и просто наблюдать, как они растут.',
      'project.7.features.1': '5 ботов под 5 тематик: история, психология, финансы, конспирология, карьера',
      'project.7.features.2': 'Каждый генерирует тему поста через локальный ИИ',
      'project.7.features.3': 'Пишет текст поста',
      'project.7.features.4': 'Генерирует картинку под текст',
      'project.7.features.5': 'Публикует пост в канал',
      'project.7.features.6': 'Управление прямо в Telegram: смена режимов, промптов, расписания',
      'project.7.how.text': 'Каждый бот — отдельный процесс на <code>Python</code>. Подключается к локальному ИИ (для текста) и к модели генерации изображений. По расписанию (или по команде) бот создаёт пост, прикрепляет картинку и отправляет в канал через <code>Bot API</code>.',
      'project.7.code.comment': '# Генерация и публикация поста',

      'project.8.about.text': 'Личное портфолио, которое вы сейчас читаете. Тёмное техно-настроение, оранжево-жёлтые акценты, куча интерактивов. Написан с нуля, без фреймворков.',
      'project.8.why.text': 'Я хотел место, где можно показать свои проекты, рассказать истории и дать людям способ связаться. И заодно потренироваться в веб-разработке на реальной задаче.',
      'project.8.features.1': 'Частицы по всему сайту, реагируют на курсор',
      'project.8.features.2': 'Клик по пустому месту добавляет новую звезду',
      'project.8.features.3': 'Терминал с физикой букв: пишешь текст, жмёшь «ОТОРВАТЬ», буквы падают и их можно кидать',
      'project.8.features.4': 'Свечение вокруг курсора на карточках',
      'project.8.features.5': 'Плавное появление блоков при скролле',
      'project.8.features.6': 'Прогресс-бары растут с процентами',
      'project.8.features.7': 'Карусель отзывов, FAQ, Timeline',
      'project.8.features.8': 'Тёмная / светлая / авто тема',
      'project.8.features.9': 'Переключатель RU/EN',
      'project.8.features.10': 'Адаптив под мобильные и iOS',
      'project.8.how.text': 'Чистый <code>HTML</code>, <code>CSS</code> и <code>JavaScript</code>. Никаких библиотек — всё написано с нуля. Частицы — на <code>canvas</code> с собственной физикой. Терминал — отдельный модуль с обработкой коллизий букв. Появление при скролле — <code>IntersectionObserver</code>.',
      'project.8.code.comment': '// Физика буквы в терминале',
      'project.4.code.c1': '# Загружаем контекст',
      'project.4.code.c2': '# Получаем ответ от локального ИИ',
      'project.4.code.c3': '# Отправляем от лица пользователя',
      'date.may.jun.2026': 'Май–Июнь 2026',
      'project.7.code.c1': '# Генерируем тему и текст',
      'project.7.code.c2': '# Генерируем картинку',
      'project.7.code.c3': '# Публикуем в канал',
      'project.8.code.c1': '// Отскок от пола',
            'story.1.title': 'Первая попытка',
      'story.1.p1': 'Программировать я пытался начать ещё в октябре 2023 года. Тогда мне захотелось делать игры, как у больших студий, только свои. Я открыл Unity, посмотрел туториалы и ничего не понял. C#, сцены, компоненты, префабы, коллайдеры - всё это было слишком сложно. Я тогда вообще не понимал, что такое программирование, думал, что это что-то вроде волшебства, где надо просто знать секретные слова.',
      'story.1.p2': 'Полгода я тыкался в Unity, смотрел ролики на ютубе, пытался делать простые сцены, но каждый раз застревал на чём-то элементарном. В итоге забросил.',
      'story.1.p3': 'Прошло ещё полгода. Я вернулся, но уже к Python. И знаешь, что стало первым проектом? Не игра, не бот, а простая утилита.',
      'story.1.p4': 'Дело в том, что Telegram, когда скачиваешь историю чата, разбивает её на кучу файлов. У меня было штук пять или больше, и в каждом гора мусора: прочитано, изменено, переслано, закреплено и прочая шелуха. Я решил это исправить. Написал скрипт, который оставлял только дату, время, отправителя и само сообщение, а всё остальное вырезал. Скрипт кидался в папку с txt-файлами, запускался через терминал и за секунды делал то, что вручную я бы разгребал часами. Написал я его за пару дней.',
      'story.1.p5': 'Помню, когда он сработал первый раз, я просто сидел и смотрел на экран, не веря, что это работает. Я запускал его снова и снова, открывал получившийся файл и проверял каждую строчку. Тогда я впервые почувствовал, что программирование - это не магия, а просто логика и терпение.',
      'story.1.p6': 'Следующим проектом были боты для Telegram-каналов, но это уже другая история.',
            'page.stories.title': 'Мои',
      'page.stories.title.accent': 'истории',
      'page.stories.subtitle': 'Жизненные истории, как я делал проекты, что учил, о чём думал. Пишу редко, но метко.',
            'story.2.title': 'Империя, которая не выросла',
      'story.3.title': '2025 год. Мой путь в колледж',
            'story.2.p1': 'Идея была моя собственная: построить империю автоматизированных Telegram-каналов. Пять тематик: история, психология, финансы, конспирология, карьера. Каждый бот сам генерирует тему, пишет пост, рисует картинку, публикует. Я только наблюдаю, как всё работает.',
      'story.2.p2': 'На каждого ушло по три дня. Использовал LM Studio, локальный ИИ, никаких внешних сервисов. Картинки собирались из спрайтов, без нейросетей.',
      'story.2.p3': 'Каналы не росли: шесть человек на пике. Основная проблема оказалась не в коде, а в том, что каждый день нужно было запускать программу.',
      'story.2.p4': 'Каналы я оставил, они до сих пор с постами. Из этого опыта я понял, что мне интереснее писать код, чем вести готовые проекты.',
            'story.3.p1': 'В 2025 году я поступил в Аграрный колледж имени Н. Т. Козлова на специальность «Системное и сетевое администрирование». Почему именно аграрный? В городе всего два колледжа, и в аграрке учился мой отец. Я сначала хотел в другой, но потом что-то ёкнуло внутри, и я подал документы сюда. Родители поддержали.',
      'story.3.p2': 'Первый день запомнился двумя вещами. Первая: большинство людей оказались очень хорошими, я быстро со всеми познакомился. Вторая: я увидел девушку, и она мне сразу понравилась, но я ей никогда не признаюсь. Наверное, это так и останется моей маленькой тайной.',
      'story.3.p3': 'Из предметов больше всего нравится «Основы алгоритмизации и программирования». А вот «Элементы высшей математики» терпеть не могу, там одни формулы и ничего понятного.',
      'story.3.p4': 'Отдельно хочу сказать про Артёма Соловьёва, преподавателя по основам алгоритмизации. Он объясняет так, что даже сложные темы становятся понятными, и с ним пары проходят легко.',
      'story.3.p5': 'С одногруппниками у меня нормальные отношения, могу с любым поговорить. Что даёт мне колледж? Знания, аттестат и время на проекты. После колледжа планирую сразу работать.',
      'story.4': 'Почему я сделал Альфу', 
      'story.prev.4.date': 'Май 2026',
      'story.prev.4.title': 'Почему я сделал Альфу',
      'story.prev.4.desc': 'Мой браузер слил пароли. Я разозлился и сделал свой. Плюс P.S. с девизом.',
      'story.4.p1': 'Всё началось с того, что я заметил подозрительные входы в свои аккаунты. Сначала подумал: показалось. На следующий день пришло уведомление: успешный вход с других стран. Тут я насторожился.',
      'story.4.p2': 'Стал разбираться и понял, что пароли сливал мой браузер. Они были сгенерированы самим браузером, никто кроме него их не знал, я их нигде не оставлял. А теперь они гуляли по чужим рукам. Я офигел. Быстро сменил все пароли, удалил браузер вместе с историей и сохранёнными данными. Осадок остался.',
      'story.4.p3': 'И тогда я подумал: почему бы не сделать свой браузер? Такой, который точно ничего не сливает. Мне хотелось знать, что он делает, и быть уверенным в нём. Выбрал Electron, потому что это самое удобное для новичка: там уже есть готовые библиотеки, и можно писать на знакомых HTML, CSS и JavaScript, а не учить что-то новое.',
      'story.4.p4': 'Работал пару недель. Самым сложным было сделать верхнюю панель с вкладками, настройками и адресной строкой. Хотелось, чтобы выглядело как у взрослых браузеров, много раз переделывал.',
      'story.4.p5': 'Первый раз, когда в моём браузере загрузился сайт, я чуть не заорал от радости. Когда доделал всё, что планировал, понял: готово. Благодаря своему браузеру я понял, как они устроены изнутри.',
            'form.sending': 'Отправка...',
      'form.success': '✓ Спасибо! Я свяжусь с вами.',
      'form.error': '✗ Ошибка. Попробуйте ещё раз или напишите в Telegram.',
      'section.tools': 'Что я',
      'section.tools.accent': 'использую',
      'tool.vscode': 'Основной редактор',
      'tool.git': 'Контроль версий',
      'tool.ollama': 'Локальные ИИ-модели',
      'tool.figma': 'Дизайн и макеты',
      'tool.photoshop': 'Обработка картинок',
      'tool.node': 'Серверный JS',
      'tool.python': 'Скрипты и боты',
      'tool.telegram': 'Боты и интеграции',
      'section.snake': 'Мини-',
      'section.snake.accent': 'игра',
      'snake.score': 'Счёт:',
      'snake.start': 'Заново',
      'snake.hint': 'Управление: стрелки на клавиатуре',
      // ===== FOOTER =====
      'footer.copy': '© 2026 YURA_DEV — Все права защищены',
    },

    en: {
      // ===== NAV =====
      'nav.home': 'Home',
      'nav.projects': 'Projects',
      'nav.stories': 'Stories',
      'nav.gallery': 'Gallery',
      'nav.about': 'About',
      'nav.contact': 'Contact',

      // ===== PROJECTS DROPDOWN =====
      'project.1': 'Alpha Browser',
      'project.2': 'Ten Assistant',
      'project.3': 'Marketplace Simulator',
      'project.4': 'AI Auto-Responder Bot',
      'project.5': 'Physics Tests',
      'project.6': 'Telegram Chat Analyzer',
      'project.7': 'Telegram Channel Bots',
      'project.8': 'Portfolio Website',

      // ===== STORIES DROPDOWN =====
      'story.1': 'First Attempt',
      'story.2': 'The Empire That Never Grew',
      'story.3': '2025. My College Path',
      'story.4': 'Why I Built Alpha',

      // ===== HERO =====
      'hero.available': '● Available for projects',
      'hero.city': '📍 Kolomna, Russia',
      'hero.stack': '💻 Python · JS · C++',
      'hero.greeting': "Hi, I'm",
      'hero.name': 'Yura',
      'hero.desc': 'Developer from Kolomna. I code in Python, JavaScript, and C++. Studying at Agrarian College named after N. T. Kozlov. Building projects and writing stories.',
      'hero.quote': '"Everything has its time"',
      'hero.btn.projects': 'View works',
      'hero.btn.contact': 'Get in touch',

      // ===== SECTIONS =====
      'section.works': 'My',
      'section.works.accent': 'works',
      'section.works.all': 'all projects →',
      'section.stories': 'My',
      'section.stories.accent': 'stories',
      'section.stories.all': 'all stories →',
      'section.skills': 'My',
      'section.skills.accent': 'skills',
      'section.stats': 'About me in',
      'section.stats.accent': 'numbers',
      'section.now': "Currently working on",
      'section.reviews': 'What people',
      'section.reviews.accent': 'say',
      'section.faq': 'Frequently asked',
      'section.faq.accent': 'questions',
      'section.timeline': 'My',
      'section.timeline.accent': 'path',
      'section.gallery.accent': 'Gallery',
      'section.gallery.all': 'full gallery →',
      'section.contact': 'Get in',
      'section.contact.accent': 'touch',

      // ===== WORKS =====
      'work.more': 'Read more',
      'work.p1.cat': 'Electron · JS',
      'work.p1.title': 'Alpha Browser',
      'work.p1.desc': 'Custom Electron browser: tabs, search history, downloads, UI customization. Fully under my control — no data leaks.',
      'work.p2.cat': 'Python · AI',
      'work.p2.title': 'Ten Assistant',
      'work.p2.desc': 'Desktop assistant with local AI: opens apps, works with folders, sends Telegram messages as a bot. Remembers context, model is swappable.',
      'work.p3.cat': 'HTML · CSS · JS',
      'work.p3.title': 'Marketplace Simulator',
      'work.p3.desc': 'DNS-style web shop: product catalog, cart, sign up with password. A full marketplace — just for myself.',

      // ===== STORIES PREVIEW =====
      'story.prev.1.date': '2023-2024',
      'story.prev.1.title': 'First Attempt',
      'story.prev.1.desc': 'How I tried Unity, dropped it, came back to Python and wrote my first script.',
      'story.prev.2.date': 'October 2025',
      'story.prev.2.title': 'The Empire That Never Grew',
      'story.prev.2.desc': '5 Telegram channels with auto-posting via local AI. The channels never took off.',
      'story.prev.3.date': '2025',
      'story.prev.3.title': '2025. My College Path',
      'story.prev.3.desc': 'How I entered Agrarian College, what I study there, and how it connects to programming.',

      // ===== STATS =====
      'stats.projects': 'Projects',
      'stats.stories': 'Stories',
      'stats.langs': 'Languages',
      'stats.start': 'Start year',

      // ===== NOW WORKING =====
      'now.cat': '● Currently working on',
      'now.title': 'Portfolio Website (this site)',
      'now.desc': 'Building my personal portfolio with interactives, dark theme, and language switcher. Doing everything myself: HTML, CSS, JS.',

      // ===== FAQ =====
      'faq.q1': 'Who are you and what do you do?',
      'faq.a1': "I'm Yura, a developer from Kolomna. I code in Python, JavaScript, and C++. Studying at Agrarian College named after N. T. Kozlov. I build projects of different scales: from bots to browsers.",
      'faq.q2': 'What programming languages do you know?',
      'faq.a2': 'Main: Python, JavaScript, C++. Additional: HTML/CSS, Git, Linux, Electron. I work with local AI models. Always learning new things.',
      'faq.q3': 'Can I order a project from you?',
      'faq.a3': 'Yes, I am open to offers. Message me on Telegram (@ArishaBii) or email — we will discuss the task, timeline, and price.',
      'faq.q4': 'How can I contact you?',
      'faq.a4': 'Telegram (@ArishaBii), GitHub (NekitTRF) or email (nekit19980@gmail.com). All contacts are on the "Contact" page or in the footer.',
      'faq.q5': 'Do you work only in Kolomna?',
      'faq.a5': 'No, I work remotely. I can build projects for clients from any city.',
      'faq.q6': 'How much does a project cost?',
      'faq.a6': 'Depends on the task. Write what you need — we will discuss and agree. Small projects I do fast.',

      // ===== TIMELINE =====
      'tl.2024.year': '2024',
      'tl.2024.text': '<b>Started programming.</b> First Python scripts, first bugs, first "it works!".',
      'tl.2025a.year': '2025',
      'tl.2025a.text': '<b>Entered Agrarian College named after N. T. Kozlov.</b> First serious project and first dive into C++.',
      'tl.2025b.year': '2025',
      'tl.2025b.text': '<b>Built Telegram channel bots.</b> 5 topics, local AI, auto-posting. First taste of real automation.',
      'tl.2026.year': '2026',
      'tl.2026.text': '<b>Year of projects.</b> Alpha browser, Ten assistant, marketplace simulator, chat analytics. And this site.',
      'tl.now.year': 'Now',
      'tl.now.text': '<b>Keep building.</b> Writing code, learning new things, growing my portfolio. More to come.',

      // ===== CONTACT =====
      'contact.telegram': 'Telegram',
      'contact.telegram.desc': '@ArishaBii — fastest way',
      'contact.github': 'GitHub',
      'contact.github.desc': 'github.com/NekitTRF — my projects',
      'contact.email': 'Email',
      'contact.email.desc': 'nekit19980@gmail.com — for serious matters',
      'contact.location': 'Location',
      'contact.location.desc': 'Kolomna, Russia',

      // ===== FORM =====
      'form.name': 'Name',
      'form.name.placeholder': 'What is your name?',
      'form.email': 'Email',
      'form.email.placeholder': 'example@mail.com',
      'form.message': 'Message',
      'form.message.placeholder': 'Describe your task or just say hi...',
      'form.send': 'Send message',

            // ===== REVIEWS =====
      'rev.1.text': '"Yura is a normal student. Submits work on time, doesn\'t skip classes. He gets math, doesn\'t just memorize it. Sometimes too serious — but that\'s more of a plus."',
      'rev.1.name': 'Olga',
      'rev.1.role': 'College teacher',
      'rev.2.text': '"We\'ve been studying together for two years now. He\'s the guy who never skips classes and always knows what homework was assigned. If I miss something — I go to him. Though he doesn\'t reply right away, always digging into his projects. But he explains well, no fluff."',
      'rev.2.name': 'Timofey',
      'rev.2.role': 'Classmate',
      'rev.3.text': '"Yura is a responsible and independent student. Two years of study, not a single absence without a valid reason. Always delivers what he promises — sometimes even more than needed. He has a clear goal and a plan for the future, which is rare for his age. The only thing — sometimes he takes on too much and burns out. But that passes. I recommend him as a reliable and determined person."',
      'rev.3.name': 'Regina',
      'rev.3.role': 'Curator',
      'rev.4.text': '"Worked with him on his portfolio. If something doesn\'t work — he doesn\'t give up, digs to the end. Can sit over one line for hours. Stubborn. I like it."',
      'rev.4.name': 'ARIA',
      'rev.4.role': 'Mentor',

      // ===== TERMINAL =====
      'term.placeholder': '> type something...',
      'term.status': '$ type what you want',
      'term.status.ready': '$ press "TEAR OFF" when ready',
      'term.status.max': '$ max 8 lines, press TEAR OFF',
      'term.status.phys': '$ grab letters and throw them',
      'term.reset': 'RESET',
      'term.tear': 'TEAR OFF',
      'term.on': 'ON',
            'page.projects.title': 'My',
      'page.projects.title.accent': 'projects',
      'page.projects.subtitle': 'Everything I have built: from simple scripts to full projects. Python, JavaScript, C++.',
      'filter.all': 'All',
      'filter.python': 'Python',
      'filter.js': 'JavaScript',
      'filter.cpp': 'C++',
      'work.p4.cat': 'Python · AI',
      'work.p4.title': 'AI Auto-Responder Bot',
      'work.p4.desc': 'Telegram bot via Business Mode, replies on my behalf using local AI.',
      'work.p5.cat': 'HTML · CSS · JS',
      'work.p5.title': 'Physics Tests',
      'work.p5.desc': 'Collection of interactive tests on physics and medicine. Exam mode, navigation, images.',
      'work.p6.cat': 'Python',
      'work.p6.title': 'Telegram Chat Analyzer',
      'work.p6.desc': 'Local script for Telegram chat analysis: top posters, media, words, HTML report.',
      'work.p7.cat': 'Python · AI',
      'work.p7.title': 'Telegram Channel Bots',
      'work.p7.desc': 'Set of bots for 5 thematic channels with auto-generated posts.',
      'work.p8.cat': 'HTML · CSS · JS',
      'work.p8.title': 'Portfolio Website',
      'work.p8.desc': 'This site: particles, terminal with letter physics, themes, RU/EN.',
            'page.gallery.title': 'Gallery',
      'page.gallery.subtitle': 'Project screenshots, coding photos, atmospheric shots. Click to enlarge.',

      'page.about.title': 'About',
      'page.about.title.accent': 'me',
      'page.about.p1': "My name is Yura. I'm a developer from Kolomna, studying at Agrarian College named after N. T. Kozlov. I code in Python, JavaScript, and C++.",
      'page.about.p2': 'Started programming in 2024 with simple Python scripts. Now I build more serious projects: from Telegram bots to websites. Everything I know I learned myself, through practice and mistakes.',
      'page.about.p3': 'I love clean code, clear interfaces, and tasks that make you think. I run this site to show my work and share stories.',
      'page.about.p4': "I'm 16 and studying at college. I code every day, try new things, and build projects that interest me. I believe the best way to learn is by doing.",

      'page.about.skills': 'What I',
      'page.about.skills.accent': 'can do',
      'page.about.facts': 'Some',
      'page.about.facts.accent': 'facts',

      'fact.1': 'Born: January 17, 2010',
      'fact.2': 'Living in Kolomna, Russia',
      'fact.3': 'Studying at Agrarian College named after N. T. Kozlov (since 2025)',
      'fact.4': 'Coding since 2024',
      'fact.5': 'Main stack: Python, JavaScript, C++',
      'fact.6': 'Working with local AI models',
      'fact.7': 'I love dark UI themes (this site included)',
      'fact.8': 'Open to work and collaboration offers',

      'page.contact.title': 'Get in',
      'page.contact.title.accent': 'touch',
      'page.contact.subtitle': 'Write about anything: order a project, ask a question, just say hi. I usually reply within a day.',

      'project.back': '← All projects',
      'project.about': 'About',
      'project.about.accent': 'the project',
      'project.why': 'Why',
      'project.why.accent': 'I built it',
      'project.features': 'What it',
      'project.features.accent': 'can do',
      'project.how': 'How it',
      'project.how.accent': 'works',
      'project.code': 'Code',
      'project.code.accent': 'snippet',
      'project.gallery': 'Gallery',
      'project.links': 'Links',
      'project.soon': 'Repository coming soon',
      'project.github': 'Open on GitHub',
      'project.demo': 'Try in Telegram',

      'story.back': '← All stories',
      'story.read.next': 'Read',
      'story.read.next.accent': 'next',
      'story.ps.title': 'P.S.',
      'story.ps.motto': 'My motto: think, speak, do',
      'story.ps.p1': 'Probably worth explaining why I write this at all. For me, programming is not just code — it is the ability to create something of my own, understand how everything works inside, and not depend on others\' decisions.',
      'story.ps.p2': 'Like when I once assembled my first computer, now I am assembling my first projects.',

      'tag.story.path': 'Path story',
      'tag.story.project': 'Project story',
      'tag.study': 'About studies',
      'read.4min': '4 min read',
      'read.3min': '3 min read',
      'read.2min': '2 min read',
      'read.1min': '1 min read',
      'date.may.2026': 'May 2026',
      'project.type.personal': 'Personal project',
            'project.1.about.text': 'Alpha Browser is my own Electron-based browser. A full desktop app with tabs, search history, download manager, and UI customization. Fully under my control — no data leaks to third parties.',
      'project.1.why.text': "My main browser (won't name it) once leaked my passwords — and a couple of my accounts got hacked. I got angry, sat down, and thought: why not build my own? That's how Alpha was born.",
      'project.1.features.1': 'Tabs — open, close, switch',
      'project.1.features.2': 'Search and browsing history',
      'project.1.features.3': 'Download manager with progress',
      'project.1.features.4': 'UI customization: themes, fonts, layout',
      'project.1.features.5': 'Works offline — data stored locally',
      'project.1.features.6': 'No trackers, no analytics',
      'project.1.how.text': 'Alpha is built on Electron — it lets me use web technologies (HTML, CSS, JavaScript) to create a desktop app. Main tabs are <code>webview</code> tags, each with its own session. History and downloads are stored in localStorage and IndexedDB.',
      'project.1.code.comment': '// Create a new tab',
            'project.type.study': 'Study project',
      'project.type.open': 'Open Source',

      'project.2.about.text': 'Ten is a desktop voice assistant that lives on my computer. Powered by local AI, remembers context, can open apps, work with folders, send Telegram messages as a bot, and open websites.',
      'project.2.why.text': "I watched an Iron Man movie and thought: why don't I have my own Jarvis? That's how Ten was born. I wanted an assistant that actually helps, not just answers questions.",
      'project.2.features.1': 'Opens apps by voice or text command',
      'project.2.features.2': 'Works with folders: create, move, delete files',
      'project.2.features.3': 'Opens websites in browser',
      'project.2.features.4': 'Sends Telegram messages as a bot',
      'project.2.features.5': 'Works with local AI — model is swappable',
      'project.2.features.6': 'Has memory: remembers what I said earlier',
      'project.2.features.7': 'Understands context, not just single commands',
      'project.2.how.text': 'Core is written in <code>Python</code>. Command recognition uses local AI (you can plug in different models via Ollama or LM Studio). UI is <code>HTML</code> + <code>CSS</code>, wrapped in a simple window. Memory is stored in a JSON file, all logic is split into modules.',
      'project.2.code.comment': '# Process command via local AI',

      'project.3.about.text': 'Marketplace Simulator is a DNS-style website. Product catalog, cart, signup and login with password. A full online store — just for myself.',
      'project.3.why.text': "Simple idea: I wanted to buy a bunch of things but couldn't. So I made my own marketplace — to at least virtually add everything to the cart.",
      'project.3.features.1': 'Product catalog with categories',
      'project.3.features.2': 'Cart: add, remove, change quantity',
      'project.3.features.3': 'Total price calculation',
      'project.3.features.4': 'Signup and login with password',
      'project.3.features.5': 'Cart saved between sessions',
      'project.3.features.6': 'Mobile responsive',
      'project.3.how.text': 'Pure <code>HTML</code>, <code>CSS</code>, <code>JavaScript</code> without frameworks. Products are in a JS array, cart and users stored in <code>localStorage</code>. Auth is simple, local (a real site needs a server, but the goal here was practice).',
      'project.3.code.comment': '// Add product to cart',

      'project.4.about.text': 'Telegram bot that replies on my behalf via Business Mode. Runs on local AI, understands context, remembers messages. Reply modes and prompts are managed right inside Telegram.',
      'project.4.why.text': "People just got tired of messaging me. Same thing over and over, always having to reply. I thought: what if a bot replied for me — intelligently, not with templates?",
      'project.4.features.1': 'Replies for me via Telegram Business Mode',
      'project.4.features.2': 'Runs on local AI — data stays on my computer',
      'project.4.features.3': 'Understands conversation context',
      'project.4.features.4': 'Stores messages in a JSON file',
      'project.4.features.5': 'Multiple reply modes (formal, friendly, short)',
      'project.4.features.6': 'Managed right in Telegram: change prompts, modes',
      'project.4.how.text': 'Core is in <code>Python</code> + a library for Telegram Bot API. Via Business Mode, the bot connects to my personal chats. Every incoming message goes to the local AI, the reply comes back and is sent as me. All messages are saved in <code>memory.json</code> for context.',
      'project.4.code.comment': '# Handle incoming message',

      'project.5.about.text': 'A collection of interactive tests on physics and medicine. Each test is a separate HTML page with questions, answer options, and score calculation. Includes an exam mode and section navigation.',
      'project.5.why.text': "Was preparing for exams and realized cramming is boring. Made tests to check myself and practice layout. Then added a medicine section — just because it was interesting.",
      'project.5.features.1': 'Tests on atomic, nuclear, wave and quantum optics, radio communication',
      'project.5.features.2': 'Medicine test',
      'project.5.features.3': 'Exam mode',
      'project.5.features.4': 'Navigation between sections',
      'project.5.features.5': 'Antenna images (drawn in SVG myself)',
      'project.5.features.6': 'Score counting and result output',
      'project.5.how.text': 'Each test is a separate <code>HTML</code> file with embedded questions and <code>JavaScript</code> logic. Styles are separate, images are SVG. No libraries, everything written from scratch.',
      'project.5.code.comment': '// Check answer in test',

      'project.6.about.text': 'Local script for Telegram chat analysis. Works with JSON export from Telegram Desktop — no internet needed, no tokens required. Counts stats, builds charts, and generates a nice dark HTML report.',
      'project.6.why.text': "I got curious about what's happening in chats I'm in. Who writes the most, at what times, what words they use. Wrote a script — got lots of insights.",
      'project.6.features.1': 'General stats: total messages, text, media, average length',
      'project.6.features.2': 'Media by category: photos, stickers, voice, video notes, GIFs',
      'project.6.features.3': 'Top-5 most active members (flooders)',
      'project.6.features.4': 'Hourly activity chart for the day',
      'project.6.features.5': 'Weekday breakdown',
      'project.6.features.6': 'Top-10 frequent words (with stop-list of prepositions)',
      'project.6.features.7': 'Dark HTML report with all charts',
      'project.6.how.text': 'Open Telegram Desktop → chat → Export history → pick JSON. Drop <code>result.json</code> into the script folder, run <code>python chat_analytics.py</code>. The script parses data and creates <code>chat_report.html</code>.',
      'project.6.code.comment': '# Top-5 most active members',

      'project.7.about.text': 'A set of bots for 5 themed Telegram channels: history, psychology, finance, conspiracy, career. Each bot uses local AI to generate a topic, write text, draw an image, and post it to the channel.',
      'project.7.why.text': 'I wanted to build an empire of automated Telegram channels. Everything working on its own: topics generated, images drawn, posts published. The idea was to launch 5 channels and just watch them grow.',
      'project.7.features.1': '5 bots for 5 topics: history, psychology, finance, conspiracy, career',
      'project.7.features.2': 'Each generates a post topic via local AI',
      'project.7.features.3': 'Writes the post text',
      'project.7.features.4': 'Generates an image to go with it',
      'project.7.features.5': 'Posts to the channel',
      'project.7.features.6': 'Managed right in Telegram: modes, prompts, schedule',
      'project.7.how.text': 'Each bot is a separate <code>Python</code> process. Connects to a local AI (for text) and to an image generation model. On schedule (or on command), the bot creates a post, attaches an image, and sends it to the channel via <code>Bot API</code>.',
      'project.7.code.comment': '# Generate and publish post',

      'project.8.about.text': 'A personal portfolio — the one you are reading right now. Dark tech mood, orange-yellow accents, lots of interactives. Written from scratch, no frameworks.',
      'project.8.why.text': 'I wanted a place to show my projects, tell stories, and give people a way to reach out. And also to practice web development on a real task.',
      'project.8.features.1': 'Particles all over the site, react to cursor',
      'project.8.features.2': 'Click empty space to add a new star',
      'project.8.features.3': 'Terminal with letter physics: type text, press "TEAR OFF", letters fall and can be thrown',
      'project.8.features.4': 'Glow around cursor on cards',
      'project.8.features.5': 'Smooth block appearance on scroll',
      'project.8.features.6': 'Progress bars grow with percentages',
      'project.8.features.7': 'Reviews carousel, FAQ, Timeline',
      'project.8.features.8': 'Dark / light / auto theme',
      'project.8.features.9': 'RU/EN switcher',
      'project.8.features.10': 'Mobile and iOS responsive',
      'project.8.how.text': 'Pure <code>HTML</code>, <code>CSS</code>, <code>JavaScript</code>. No libraries — everything from scratch. Particles use <code>canvas</code> with custom physics. Terminal is a separate module handling letter collisions. Scroll appearance uses <code>IntersectionObserver</code>.',
      'project.8.code.comment': '// Letter physics in terminal',
            'project.4.code.c1': '# Load context',
      'project.4.code.c2': '# Get response from local AI',
      'project.4.code.c3': '# Send as the user',
      'date.may.jun.2026': 'May–June 2026',
      'project.7.code.c1': '# Generate topic and text',
      'project.7.code.c2': '# Generate image',
      'project.7.code.c3': '# Publish to channel',
      'project.8.code.c1': '// Bounce off the floor',
            'story.1.title': 'First Attempt',
      'story.1.p1': "I first tried to start programming back in October 2023. I wanted to make games like the big studios, but my own. I opened Unity, watched tutorials and understood nothing. C#, scenes, components, prefabs, colliders — it was all too complicated. I didn't even understand what programming was back then, I thought it was like magic where you just need to know the secret words.",
      'story.1.p2': "For six months I poked around Unity, watched YouTube videos, tried to make simple scenes, but every time I got stuck on something elementary. Eventually I gave up.",
      'story.1.p3': "Another six months passed. I came back, but this time to Python. And you know what became my first project? Not a game, not a bot, but a simple utility.",
      'story.1.p4': "The thing is, when you download a Telegram chat history, it splits it into a bunch of files. I had like five or more, and each was full of garbage: read, edited, forwarded, pinned and other junk. I decided to fix that. I wrote a script that kept only the date, time, sender and the message itself, and cut out everything else. The script was dropped into a folder with txt files, ran through the terminal and in seconds did what would have taken me hours manually. I wrote it in a couple of days.",
      'story.1.p5': "I remember when it worked the first time, I just sat and stared at the screen, not believing it worked. I ran it again and again, opened the resulting file and checked every line. That was the first time I felt that programming isn't magic, but just logic and patience.",
      'story.1.p6': "The next project was bots for Telegram channels, but that's another story.",
            'page.stories.title': 'My',
      'page.stories.title.accent': 'stories',
      'page.stories.subtitle': 'Life stories, how I built projects, what I studied, what I thought about. I write rarely, but to the point.',
            'story.2.title': 'The Empire That Never Grew',
      'story.3.title': '2025. My College Path',
            'story.2.p1': 'The idea was mine: to build an empire of automated Telegram channels. Five topics: history, psychology, finance, conspiracy, career. Each bot generates a topic, writes a post, draws an image, and publishes. I just watch it work.',
      'story.2.p2': 'Each one took three days. I used LM Studio, a local AI, no external services. Images were assembled from sprites, no neural networks.',
      'story.2.p3': "The channels didn't grow: six people at peak. The main problem wasn't the code, it was that I had to launch the program every day.",
      'story.2.p4': "I left the channels — they still have posts. From this experience I realized I enjoy writing code more than running finished projects.",
            'story.3.p1': "In 2025 I entered Agrarian College named after N. T. Kozlov, majoring in System and Network Administration. Why agrarian? There are only two colleges in the city, and my father studied at this one. I initially wanted another, but something clicked inside and I applied here. My parents supported me.",
      'story.3.p2': "The first day is remembered for two things. First: most people turned out to be really good, I quickly met everyone. Second: I saw a girl, and I liked her right away, but I will never confess to her. I guess it will stay my little secret.",
      'story.3.p3': "Among the subjects, I like 'Basics of Algorithmization and Programming' the most. And 'Elements of Higher Mathematics' I can't stand — just formulas and nothing clear.",
      'story.3.p4': "Separately, I want to mention Artyom Solovyov, the teacher of algorithmization basics. He explains in a way that even complex topics become clear, and his classes go easily.",
      'story.3.p5': "I have normal relationships with my classmates, I can talk to anyone. What does college give me? Knowledge, a diploma, and time for projects. After college I plan to start working right away.",
      'story.prev.4.date': 'May 2026',
'story.prev.4.title': 'Why I Built Alpha',
'story.prev.4.desc': 'My browser leaked passwords. I got angry and built my own. Plus a P.S. with my motto.',      
      'story.4.p1': "It all started when I noticed suspicious logins to my accounts. At first I thought: must be nothing. The next day a notification came: successful login from other countries. That got my attention.",
      'story.4.p2': "I started investigating and realized my browser was leaking passwords. They were generated by the browser itself, nobody else knew them, I never left them anywhere. And now they were in someone else's hands. I freaked out. Quickly changed all passwords, deleted the browser along with history and saved data. The aftertaste remained.",
      'story.4.p3': "And then I thought: why not build my own browser? One that definitely doesn't leak anything. I wanted to know what it does and be sure about it. I chose Electron because it's the most convenient for a beginner: it has ready-made libraries, and you can write in familiar HTML, CSS, and JavaScript instead of learning something new.",
      'story.4.p4': "Worked for a couple of weeks. The hardest part was making the top panel with tabs, settings, and address bar. I wanted it to look like grown-up browsers, redoing it many times.",
      'story.4.p5': "The first time a website loaded in my browser, I almost screamed with joy. When I finished everything I planned, I realized: done. Thanks to my browser, I understood how they work inside.",
            'form.sending': 'Sending...',
      'form.success': '✓ Thanks! I will get back to you.',
      'form.error': '✗ Error. Try again or message me on Telegram.',
      'section.tools': 'What I',
'section.tools.accent': 'use',
'tool.vscode': 'Main editor',
'tool.git': 'Version control',
'tool.ollama': 'Local AI models',
'tool.figma': 'Design & mockups',
'tool.photoshop': 'Image editing',
'tool.node': 'Server-side JS',
'tool.python': 'Scripts & bots',
'tool.telegram': 'Bots & integrations',
'section.snake': 'Mini',
'section.snake.accent': 'game',
'snake.score': 'Score:',
'snake.start': 'Restart',
'snake.hint': 'Controls: keyboard arrows',
      // ===== FOOTER =====
      'footer.copy': '© 2026 YURA_DEV — All rights reserved',
    }
  };

  function getStored() {
    return localStorage.getItem('lang') || 'ru';
  }

  function apply(lang) {
    btn.textContent = lang.toUpperCase();
    document.documentElement.setAttribute('lang', lang);
    localStorage.setItem('lang', lang);

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      const text = dict[lang]?.[key];
      if (text !== undefined) {
        if (text.includes('<')) {
          el.innerHTML = text;
        } else {
          el.textContent = text;
        }
      }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      const text = dict[lang]?.[key];
      if (text !== undefined) {
        el.placeholder = text;
      }
    });
  }

  btn.addEventListener('click', () => {
    const current = getStored();
    apply(current === 'ru' ? 'en' : 'ru');
  });

  apply(getStored());
})();